using Lens.util.math;

namespace BurningKnight.util {
	public static class LoadScreenTitles {
		public static string Generate() {
			return titles[Rnd.Int(titles.Length)];
		}
		
		private static string[] titles = {
			"Please stand by",
			"Press X",
			"Generating trouble",
			"Looking cool",
			"Loading...",
			"Get em!",
			"Generating generators",
			"Submitting an issue",
			"Terraforming mars",
			"I think that knight wanted to say something",
			"Are we there yet?",
			"Generating secrets",
			"Hiding secrets",
			"I'm hungry",
			"/!\\ /!\\ /!\\",
			"Saving is important",
			"Cooling down",
			"Heating up",
			"Adding some drama",
			"You better get digging",
			"F2",
			"Generating generators",
			"Waking up",
			"Deleting the saves",
			"Preparing to start",
			"Looking for an excuse",
			"Automatically synchronizing cardinal grammeters",
			"Reducing sinusoidal repleneration",
			"Fromaging the bituminous spandrels",
			"Join our discord!",
			"Reticulating splines",
			"Calculating Math.PI",
			"Inventing the wheel",
			"Adding some oil",
			"Recruiting robot hamsters",
			"Generating buttons",
			"Installing deinstallers",
			"Thinking",
			"I like pizza",
			"That fight tho",
			"Be careful",
			"Almost alive",
			"@egordorichev",
			"Dog food",
			"Always wear dry socks",
			"Its your lucky day",
			"Press F to pay respect",
			"Let's do this",
			"Let's go",
			"YOOOOOO",
			"This is a joke mimic",
			"Go go go",
			"Делаем вид что это что-то значит",
			"Loading terrain",
			"Building terrain",
			"Googling",
			"Generating more enemies",
			"Sending help",
			"SOS",
			"Are we lost?",
			"Spooooky",
			"On fire",
			"It's magic time",
			"Settings things on fire",
			"Preparing to explode",
			"Installing linux",
			"Erasing data",
			"Generating a joke"
		};
	}
}